//GET method
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const GET_ALL_CONTACTS_STARTED = 'GET_ALL_CONTACTS_STARTED';
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_FAILURE = 'GET_ALL_CONTACTS_FAILURE';

//POST method
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE';
export const ADD_CONTACT_STARTED = 'ADD_CONTACT_STARTED';
// PUT method todo
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE';
export const UPDATE_CONTACT_STARTED = 'UPDATE_CONTACT_STARTED';
//DELETE method todo
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';
export const DELETE_CONTACT_STARTED = 'DELETE_CONTACT_STARTED';